import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import classes from "./page.module.css"

import MainNavBar from "./_components/navBar/NavBar";
import { useRouter } from "next/router";
import { useSelectedLayoutSegment } from "next/navigation";
import Footer from "./_components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pet-Care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode,
  modal: React.ReactNode,
}>) {

  console.log(modal)

  return (
    <html lang="en">
        <body className={inter.className}>
            <main className={classes.main}>
                <div className={classes.navContainer}>
                    <MainNavBar></MainNavBar>
                </div>

                <div className={classes.contentContainer}>
                    {children}
                </div>
                <div className={classes.footerContainer}>
                    <Footer></Footer>
                </div>
                {modal}
            </main>
        </body>
    </html>
  );
}
